// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package lobby

import (
	vector "github.com/jiangshuai341/zbus/build/fb/vector"
)

type LobbyPlayerEntityProxy struct {
}

func NewLobbyPlayerEntityProxy(keyhash int64, netdriver int32) *LobbyPlayerEntityProxy {
	//初始化网络消息发射器
	return nil
}
func (p *LobbyPlayerEntityProxy) StoreSync(in Monster) (*vector.Vec3, error) {

}
func (p *LobbyPlayerEntityProxy) StoreAsync(in Monster) (*vector.Vec3, error) {

}

func (p *LobbyPlayerEntityProxy) BindMaxHpChange(in Monster) (*vector.Vec3, error) {

}

type ILobbyPlayerServiceImp interface {
}
type LobbyPlayerEntity struct {
	imp ILobbyPlayerServiceImp
}

func CreateLobbyPlayerEntity(netdriver int32, imp ILobbyPlayerServiceImp, netdriver int32) *LobbyPlayerEntity {
	//在Gproxy上注册
	//在RpcProcessor上注册
	//初始化网络消息发射器
	return nil
}

func (e *LobbyPlayerEntity) MaxHpChangeBroadcast(in Monster, callback func(*vector.Vec3, error)) {

}
